#! /usr/bin/env python
import sys
import shutil
import os
import glob
import fileinput

args = sys.argv[1:]

def create_project(project_name):

    shutil.copytree('/home/crepe/projects/skeleton/',('/home/crepe/projects/%s') % project_name)
    root_dir = '/home/crepe/projects/%s' % project_name

    for dirname, subdir, filename in os.walk(root_dir):
        if dirname.split('/')[-1] == 'NAME':
            new_name = '/'.join(dirname.split('/')[:-1]) 
            shutil.move(dirname,new_name + '/' + project_name)
    
    rename_dir = root_dir + '/*/*_tests.py'
    for file in glob.glob(rename_dir):
        new_name = '/'.join(file.split('/')[:-1])
        print new_name
        shutil.move(file,new_name + '/' + project_name + '_tests.py')

    for root, subdir, files in os.walk(root_dir):
        for filename in files:
            for line in fileinput.input(os.path.join(root,filename), inplace=True):
                print line.replace('NAME',project_name)
        

create_project('test_function')


